<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ir.moke.orchestra</groupId>
    <artifactId>template</artifactId>
    <version>0,1</version>
    <name>template-modules</name>

    <url>https://github.com/Orchestra-System/template</url>
    <dependencies>

        <!-- Orchestra API -->
        <dependency>
            <groupId>ir.moke.orchestra</groupId>
            <artifactId>orchestra-api</artifactId>
            <version>0.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- Groovy -->
        <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy</artifactId>
            <version>5.0.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy-json</artifactId>
            <version>5.0.3</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>25</release>
                </configuration>
            </plugin>

            <!-- Groovy -->
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>4.3.1</version>
                <configuration>
                    <targetBytecode>25</targetBytecode>
                    <skipTests>true</skipTests>
                    <skipBytecodeCheck>true</skipBytecodeCheck>
                    <skipScriptExecution>true</skipScriptExecution>
                    <skipGroovyDoc>true</skipGroovyDoc>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
